export const DEVELOPER_PROJECTS = [
  {
    id: "1",
    title: "AI Finance Advisor",
    description: "AI-powered financial planning and management assistant.",
    image: "https://images.unsplash.com/photo-1551650975-87deedd944c3?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["React", "AI/ML", "FinTech"],
    action: "View Live",
    url: "https://ai-finance-advisor.vercel.app",
  },
  {
    id: "2",
    title: "Crypto AutoTrader",
    description: "Automated crypto trading platform with strategy execution.",
    image: "https://images.unsplash.com/photo-1518546305927-5a555bb7020d?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["Next.js", "Crypto", "Trading"],
    action: "View Live",
    url: "https://crypto-autotrader.vercel.app",
  },
  {
    id: "3",
    title: "FlowX Exchange",
    description: "Financial platform for exchange, wallet, and more.",
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["TypeScript", "Blockchain", "Exchange"],
    action: "View Live",
    url: "https://flowx-exchange.vercel.app",
  },
  {
    id: "4",
    title: "CloudCost Optimizer",
    description: "Multi-cloud cost optimization and monitoring dashboard.",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["React", "Cloud", "Analytics"],
    action: "View Live",
    url: "https://cloudcost-optimizer.vercel.app",
  },
  {
    id: "5",
    title: "SecureVault CLI",
    description: "CLI tool for managing secrets, passwords, and API keys securely.",
    image: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["CLI", "Security", "DevTools"],
    action: "View Live",
    url: "https://securevault-cli.vercel.app",
  },
  {
    id: "6",
    title: "CEO API Vault",
    description: "Centralized API vault for developers.",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["API", "Management", "DevTools"],
    action: "View Live",
    url: "https://ceoapivault.vercel.app",
  },
  {
    id: "7",
    title: "CodeMentor Academy",
    description: "Interactive coding and IT/business academy.",
    image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["Education", "Coding", "Academy"],
    action: "View Live",
    url: "https://codementor-academy.vercel.app",
  },
  {
    id: "8",
    title: "DevFlow CLI",
    description: "Open-source CLI for developer workflows.",
    image: "https://images.unsplash.com/photo-1629654297299-c8506221ca97?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["CLI", "DevTools", "Workflow"],
    action: "View Live",
    url: "https://devflow-cli.vercel.app",
  },
  {
    id: "9",
    title: "AI Utility Hub",
    description: "Comprehensive hub of AI tools and utilities.",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["React", "AI Tools", "Productivity"],
    action: "View Live",
    url: "https://ai-utility-hub.vercel.app",
  },
  {
    id: "10",
    title: "Bible Game Hub",
    description: "Interactive games for biblical knowledge.",
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["React", "Education", "Gaming"],
    action: "View Live",
    url: "https://bible-game-hub.vercel.app",
  },
  {
    id: "11",
    title: "Agriverse Farm Game",
    description: "Fun and interactive farming web game.",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["Gaming", "Agriculture", "Simulation"],
    action: "View Live",
    url: "https://agriverse-farmgame.vercel.app",
  },
  {
    id: "12",
    title: "CEO AI Persona Sidekick",
    description: "AI chatbot with customizable personas.",
    image: "https://images.unsplash.com/photo-1531746790731-6c087fecd65a?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["AI", "Chatbot", "Personas"],
    action: "View Live",
    url: "https://ceoai-persona-sidekick.vercel.app",
  },
  {
    id: "13",
    title: "Clarity Tracker",
    description: "Weather + productivity tracker app.",
    image: "https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["Productivity", "Weather", "Tracking"],
    action: "View Live",
    url: "https://clarity-tracker.vercel.app",
  },
  {
    id: "14",
    title: "LifeLoop Productivity",
    description: "Comprehensive productivity suite.",
    image: "https://images.unsplash.com/photo-1611224923853-80b023f02d71?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["Productivity", "Tasks", "Goals"],
    action: "View Live",
    url: "https://lifeloop-productivity.vercel.app",
  },
  {
    id: "15",
    title: "Persona Typing Master",
    description: "Typing drills and training with different personas.",
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["Education", "Typing", "Training"],
    action: "View Live",
    url: "https://persona-typing-master.vercel.app",
  },
  {
    id: "16",
    title: "PoshPOULE Scratch Game",
    description: "Interactive farm simulation game built in Scratch with web wrapper.",
    image: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["Gaming", "Scratch", "Farm"],
    action: "View Live",
    url: "https://poshpoule-scratch-game.vercel.app",
  },
  {
    id: "17",
    title: "PPF Games & Simulations",
    description: "Farm-themed games and simulations (C++ showcase).",
    image: "https://images.unsplash.com/photo-1493711662062-fa541adb3fc8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["C++", "Gaming", "Simulation"],
    action: "View Live",
    url: "https://ppf-gamesandsimulations.vercel.app",
  },
];

export const BUSINESS_PROJECTS = [
  {
    id: "1",
    title: "CEOTR Suite",
    description: "Business ERP dashboard for comprehensive company management.",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["Leadership", "Strategy", "Management"],
    action: "View Live",
    url: "https://ceotr-suite.vercel.app",
  },
  {
    id: "2",
    title: "PoshPOULE Farms Suite",
    description: "Premium agricultural management system with sales and operations tools.",
    image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["Agriculture", "Premium", "Management"],
    action: "View Live",
    url: "https://poshpoule-farms-suite.vercel.app",
  },
  {
    id: "3",
    title: "Roka TableWater Suite",
    description: "Water supply and management solution for residential and commercial use.",
    image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["Water", "Supply", "Management"],
    action: "View Live",
    url: "https://roka-tablewater-suite.vercel.app",
  },
  {
    id: "4",
    title: "Emmdra Empire & Lifestyle",
    description: "Platform for lifestyle, fashion, beauty, DIY, and learning.",
    image: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["Luxury", "Lifestyle", "Branding"],
    action: "View Live",
    url: "https://emmdra-empireandlifestyle.vercel.app",
  },
  {
    id: "5",
    title: "Zereth Cakes & Foods Hub",
    description: "Artistic cakes and foods hub — where edible art meets extraordinary taste.",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["Food & Beverage", "E-commerce", "Premium"],
    action: "View Live",
    url: "https://zereth-cakesandfoods-hub.vercel.app",
  },
  {
    id: "6",
    title: "CEOWrites Blog",
    description: "SEO-friendly, responsive blog on technology, business, and faith.",
    image: "https://images.unsplash.com/photo-1499750310107-5fef28a66643?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["Blog", "Content", "SEO"],
    action: "View Live",
    url: "https://ceowrites-emmanuel-bloghub.vercel.app",
  },
  {
    id: "7",
    title: "EmmanuelOS SWART Dashboard",
    description: "Dynamic showcase dashboard for all apps in the portfolio.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["Dashboard", "Portfolio", "Showcase"],
    action: "View Live",
    url: "https://emmanuelos-swart-dashboard.vercel.app",
  },
  {
    id: "8",
    title: "JEPLIGOM Ministry",
    description: "Christian Liberation/Gospel Ministry fellowship.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["Ministry", "Community", "Faith"],
    action: "View Live",
    url: "https://jepligom-ministry.vercel.app",
  },
  {
    id: "9",
    title: "Jesus Power Arena",
    description: "Faith-based community events & praise platform.",
    image: "https://images.unsplash.com/photo-1438232992991-995b7058bbb3?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=250",
    tags: ["Faith", "Events", "Community"],
    action: "View Live",
    url: "https://jpa-eventandpraise.vercel.app",
  },
];

export const CLIENT_TESTIMONIALS = [
  {
    id: "1",
    name: "Sarah Johnson",
    role: "CEO, TechStart Solutions",
    company: "TechStart Solutions",
    image: "https://images.unsplash.com/photo-1494790108755-2616b612b786?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&h=150",
    testimonial: "Emmanuel's dual expertise in development and business strategy transformed our startup. His technical solutions increased our efficiency by 300% while his strategic guidance helped us secure Series A funding.",
    rating: 5,
    project: "Full-stack development & Business strategy"
  },
  {
    id: "2",
    name: "Michael Chen",
    role: "Founder, CryptoVault",
    company: "CryptoVault",
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&h=150",
    testimonial: "Working with Emmanuel on our cryptocurrency platform was exceptional. His understanding of both blockchain technology and market dynamics delivered a product that exceeded our expectations.",
    rating: 5,
    project: "Blockchain development & Market strategy"
  },
  {
    id: "3",
    name: "Priya Patel",
    role: "Director, AgriTech Innovations",
    company: "AgriTech Innovations",
    image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&h=150",
    testimonial: "Emmanuel's agricultural technology solutions revolutionized our farm management system. His strategic approach to product development helped us scale across 3 countries in 6 months.",
    rating: 5,
    project: "AgriTech platform & Scaling strategy"
  },
  {
    id: "4",
    name: "David Okafor",
    role: "Managing Director, Lagos Ventures",
    company: "Lagos Ventures",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-4.0.3&auto=format&fit=crop&w=150&h=150",
    testimonial: "Emmanuel's business acumen and technical expertise made him invaluable to our portfolio companies. His strategic guidance helped 5 of our startups achieve profitability within 12 months.",
    rating: 5,
    project: "Portfolio optimization & Growth strategy"
  }
];

export const PROFESSIONAL_SERVICES = {
  development: [
    {
      id: "dev-1",
      title: "Full-Stack Web Development",
      description: "Complete web application development with modern technologies",
      features: ["React/Next.js Frontend", "Node.js/Python Backend", "Database Design", "API Development", "Deployment & DevOps"],
      price: "₦2,500,000",
      duration: "4-8 weeks",
      category: "development"
    },
    {
      id: "dev-2", 
      title: "Mobile App Development",
      description: "Cross-platform mobile applications for iOS and Android",
      features: ["React Native/Flutter", "Native Performance", "App Store Deployment", "Push Notifications", "Offline Functionality"],
      price: "₦3,500,000",
      duration: "6-10 weeks",
      category: "development"
    },
    {
      id: "dev-3",
      title: "AI/ML Integration",
      description: "Artificial Intelligence and Machine Learning solutions",
      features: ["Custom AI Models", "Data Analysis", "Predictive Analytics", "Automation Systems", "API Integration"],
      price: "₦4,000,000",
      duration: "8-12 weeks", 
      category: "development"
    }
  ],
  business: [
    {
      id: "biz-1",
      title: "Digital Strategy Consulting",
      description: "Comprehensive digital transformation and growth strategy",
      features: ["Market Analysis", "Competitive Research", "Growth Roadmap", "Technology Stack Planning", "ROI Optimization"],
      price: "₦1,500,000",
      duration: "2-4 weeks",
      category: "business"
    },
    {
      id: "biz-2",
      title: "Brand Development & Positioning",
      description: "Complete brand identity and market positioning strategy",
      features: ["Brand Identity Design", "Market Positioning", "Content Strategy", "Social Media Strategy", "Launch Campaign"],
      price: "₦2,000,000", 
      duration: "4-6 weeks",
      category: "business"
    },
    {
      id: "biz-3",
      title: "Business Process Automation",
      description: "Streamline operations with custom automation solutions",
      features: ["Process Analysis", "Workflow Automation", "Integration Setup", "Staff Training", "Performance Monitoring"],
      price: "₦3,000,000",
      duration: "6-8 weeks",
      category: "business"
    }
  ]
};

export const SOCIAL_LINKS = [
  {
    name: "GitHub",
    url: "https://github.com/e-ogugua",
    icon: "github",
  },
  {
    name: "LinkedIn",
    url: "https://www.linkedin.com/in/emmanuelogugua",
    icon: "linkedin",
  },
  {
    name: "Twitter",
    url: "https://twitter.com/emmachuka",
    icon: "twitter",
  },
];
